import type { Metadata } from 'next'
import '../config/globals.css'
import { ThemeProvider } from '../components/ThemeProvider'
import Header from '../components/Header'
import { pretendard } from '../../public/fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${pretendard.variable} font-pretendard h-full`}
      suppressHydrationWarning>
      <body className="mx-auto h-full max-w-4xl">
        <ThemeProvider>
          <Header />

          <main className="mx-auto min-w-[320px] flex-col px-9 pt-16 sm:px-6">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
